### ISSUE TITLE
Don't relay raw notebook request to Pylance

### ISSUE THREAD

**Issue by heejaechang** [microsoft/vscode-jupyter-lsp-middleware#31]
Currently, notebook middleware sends not only LSP request for concat doc, but also relay all raw messages from notebook to us (Pylance).

currently, it works fine since we don't know how to handle notebook requests ourselves, so we drop them and only handle requests over concat docs, but soon Pylance will have ability to handle notebook request ourselves. and won't be able to know that 2 requests (notebook and concat) are actually for the same thing and process them conceptually twice.

middleware should only send concat message if jupyter.pylanceHandlesNotebooks is not set, and send only raw notebook message if it is set. but not both.

**Comment by rchiodo** [comment]
The latest bits here should have fixed this. Switching jupyter extension to actually consume them.

**Comment by heejaechang** [comment]
will it stop sending raw notebook request to default pylance server as well? we now can handle raw notebook request, but if it is sent to default pylance server (not one created by jupyter extension but created by regular python extension), we will still process them even if we will never get LSP requests for them (since jupyter extension will send those to the pylance server specifically created for the notebook)

**Comment by heejaechang** [comment]
tagging @rchiodo
