### ISSUE TITLE
Upgrade to new LSP modules for LSP notebooks support

### ISSUE THREAD

**Issue by debonte** [microsoft/vscode-jupyter-lsp-middleware#42]
The Pylance team would like to [enable notebook support](https://github.com/microsoft/pyrx/issues/2136) using the [new LSP notebooks messages](https://github.com/microsoft/vscode-languageserver-node/blob/78ee13a4bafdd831411dd3fb66c8083d3c8ca9b1/protocol/src/common/proposed.notebooks.md#L1) found in LSP 3.17. Our client, vscode-python, will also need to upgrade to enable this feature. And since vscode-python [gets Middleware objects](https://github.com/microsoft/vscode-python/blob/main/src/client/activation/languageClientMiddleware.ts#L30) from vscode-jupyter-lsp-middleware, this middleware project needs to be upgraded also.

vscode-languageclient should be upgraded to the latest 8.0.0-next package
vscode-languageserver-types should be upgraded to the latest 3.17.0-next package

The latest versions of these packages can be found at https://github.com/microsoft/vscode-languageserver-node/tags

It's possible that [lsp-notebook-concat](https://github.com/microsoft/lsp-notebook-concat) needs to be modified as part of this work. The only LSP package it references is vscode-languageserver-protocol, and I thought that the 3.16 and 3.17 protocols were compatible, but when I was trying to upgrade vscode-jupyter-lsp-middleware myself I ran into some build errors that seemed to indicate that stuff was out of sync between the two projects. I may be mistaken.

**Comment by rchiodo** [comment]
This should just be a matter of installing the latest vscode-languageclient library

**Comment by debonte** [comment]
There are breaking changes in LSP 3.17. There will be build issues to resolve after you upgrade vscode-languageclient.
