### ISSUE TITLE
Documentation for adding support for other languages

### ISSUE THREAD

**Issue by HKalbasi** [microsoft/vscode-jupyter-lsp-middleware#59]
I tried listening for experimental `notebookDocument/didOpen` but it seems vscode doesn't send these events and still uses normal `textDocument/didOpen` events. So my question is, how this interacts with a language server exactly and how a language server can detect if it is in a jupyter notebook and detect special commands (like `:deps` in the Rust language which I'm interested in).

**Comment by debonte** [comment]
@HKalbasi, you need to configure the `capabilities.notebookDocumentSync` field in your `InitializeResult` so the LSP client knows what types of notebooks you want to receive `notebookDocument` events for.

I'm closing this issue. If you have more questions along these lines, the LSP repo (https://github.com/microsoft/vscode-languageserver-node) would be a more appropriate place to ask.
